In [1]:
cd /content/drive/My Drive/Spam Classifier

/content/drive/My Drive/Spam Classifier


In [0]:
import nltk
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer,WordNetLemmatizer
from nltk.tokenize import word_tokenize
import sklearn.metrics as m
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier


In [3]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [4]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [5]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [6]:
dataset=pd.read_csv('spam.csv',encoding='latin-1')
dataset

v1  ... Unnamed: 4
0      ham  ...        NaN
1      ham  ...        NaN
2     spam  ...        NaN
3      ham  ...        NaN
4      ham  ...        NaN
...    ...  ...        ...
5567  spam  ...        NaN
5568   ham  ...        NaN
5569   ham  ...        NaN
5570   ham  ...        NaN
5571   ham  ...        NaN

[5572 rows x 5 columns]

In [0]:
sent=dataset.iloc[:,[1]]['v2']

In [8]:
sent

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: v2, Length: 5572, dtype: object

In [0]:
label=dataset.iloc[:,[0]]['v1']

In [10]:
label

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: v1, Length: 5572, dtype: object

In [0]:
from sklearn.preprocessing import LabelEncoder

In [0]:
le=LabelEncoder()
label=le.fit_transform(label)

In [13]:
label

array([0, 0, 1, ..., 0, 0, 0])

In [14]:
le.classes_

array(['ham', 'spam'], dtype=object)

In [0]:
import re

In [16]:
len(set(stopwords.words('english')))

179

In [0]:
stem=PorterStemmer()

In [18]:
sent

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: v2, Length: 5572, dtype: object

In [0]:
sentences=[]
for sen in sent:
  senti=re.sub('[^A-Za-z]',' ',sen)
  senti=senti.lower()
  words=word_tokenize(senti)
  word=[stem.stem(i) for i in words if i not in stopwords.words('english')]
  senti=' '.join(word)
  sentences.append(senti)


In [20]:
sentences

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gon na home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breathe

In [0]:
from sklearn.feature_extraction.text import CountVectorizer

In [0]:
cv=CountVectorizer(max_features=5000)

In [0]:
features=cv.fit_transform(sentences)

In [0]:
features=features.toarray()

In [25]:
features

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [26]:
len(cv.get_feature_names())

5000

In [0]:
feature_train,feature_test,label_train,label_test=train_test_split(features,label,test_size=0.2,random_state=7)

#Naive Bayies

In [28]:
model=MultinomialNB()
model.fit(feature_train,label_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [0]:
label_pred=model.predict(feature_test)

In [30]:
label_pred

array([0, 0, 0, ..., 0, 0, 0])

In [31]:
label_test

array([0, 0, 0, ..., 0, 0, 0])

In [32]:
m.accuracy_score(label_test,label_pred)

0.9856502242152466

In [33]:
print(m.classification_report(label_test,label_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       970
           1       0.93      0.96      0.95       145

    accuracy                           0.99      1115
   macro avg       0.96      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [34]:
print(m.confusion_matrix(label_test,label_pred))

[[960  10]
 [  6 139]]


#SVC

In [35]:
model=SVC(kernel='linear')
model.fit(feature_train,label_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
label_pred=model.predict(feature_test)

In [37]:
m.accuracy_score(label_test,label_pred)

0.9874439461883409

In [38]:
label_pred

array([0, 0, 0, ..., 0, 0, 0])

In [39]:
label_test

array([0, 0, 0, ..., 0, 0, 0])

In [40]:
print(m.classification_report(label_test,label_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       970
           1       0.98      0.92      0.95       145

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [41]:
print(m.confusion_matrix(label_test,label_pred))

[[967   3]
 [ 11 134]]


#LogisticRegression

In [42]:
model=LogisticRegression()
model.fit(feature_train,label_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
label_pred=model.predict(feature_test)

In [44]:
m.accuracy_score(label_test,label_pred)

0.9865470852017937

In [45]:
label_pred

array([0, 0, 0, ..., 0, 0, 0])

In [46]:
label_test

array([0, 0, 0, ..., 0, 0, 0])

In [47]:
print(m.classification_report(label_test,label_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       970
           1       0.99      0.90      0.95       145

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [48]:
print(m.confusion_matrix(label_test,label_pred))

[[969   1]
 [ 14 131]]


#Decision Tree

In [49]:
model=DecisionTreeClassifier()
model.fit(feature_train,label_train)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [0]:
label_pred=model.predict(feature_test)

In [51]:
m.accuracy_score(label_test,label_pred)

0.97847533632287

In [52]:
label_pred

array([0, 0, 0, ..., 0, 0, 0])

In [53]:
label_test

array([0, 0, 0, ..., 0, 0, 0])

In [54]:
print(m.classification_report(label_test,label_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       970
           1       0.94      0.89      0.91       145

    accuracy                           0.98      1115
   macro avg       0.96      0.94      0.95      1115
weighted avg       0.98      0.98      0.98      1115



In [55]:
print(m.confusion_matrix(label_test,label_pred))

[[962   8]
 [ 16 129]]
